name: Deploy AWS - CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build Project
        run: npm run build

			- uses: actions/upload-artifact@v1
				with:
      		name: buildfiles
        	path: build/*

	download_build:
		name: Download Build
		runs-on: self-hosted
		needs: build
		steps:
			- uses: actions/download-artifact@v1
        with:
          name: buildfiles
      - run: cat _redirects
